### ISSUE TITLE
Multi stage evaluation?

### ISSUE THREAD

**Issue by lulf** [seedwing-io/seedwing-policy#13]
At the moment, the evaluation blends I/O operations and evaluation. I think separating those concerns splitting the evaluation into a 'prepare' and 'evaluate' phases would give some benefits:

* Easier testing and benchmarking of the engine
* Scale and control I/O parallelism separately from the evaluation. The result of I/O can be cached in a controlled way, and reused for multiple parallel evaluations.
* Less arc, clone, sync, send safety in the evaluation vs the prepare stage?

This is based on my very limited understanding of the engine so far, so apologies up front for wrong assumptions!

**Comment by bobmcwhirter** [comment]
I'm unsure if this will work consistently, since `f(g(h(x))` or `f • g • h x` is legal.
But happy for exploration.

That being said, I think all `f(x)` should memoize for some configurable (by `f(x)`) period.

e.g.

`Len(some-list)` could memoize forever, where `sigstore::SHA256(...)` could memoize for ~3 minutes or whatever the deployer wants.

**Comment by bobmcwhirter** [comment]
There's a pretty good `lru` crate for bounded-sized caching (that rusty btmesh project used it).
